# name: End-to-end tests
# on: push
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6


name: End-to-End Smoke Tests

on: 
  push:
    branches:
      - master

jobs:
  cypress-smoke:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run only @smoke tests
      - name: Run Cypress Smoke Tests
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/**/*  # Include all files in the e2e folder
          env: TAGS=smoke         # Run tests with the @smoke tag
